export const BITRIX_APP_CONFIG = {
  APP_NAME: "Noticias IA",
  ENTITY_TYPE_ID: 1070,
  HISTORY: {
    ENTITY_TYPE_ID: 1070,
  },
  STATUSES: {
    PENDIENTE: "PENDIENTE",
    GENERANDO: "GENERANDO",
    GENERADA: "GENERADA",
    REVISAR: "REVISAR",
    APROBADA: "APROBADA",
    RECHAZADA: "RECHAZADA",
    ERROR_IA: "ERROR_IA",
  },
};